document.querySelector("#button").onclick = function(){

    const changePage = document.querySelector("#change");
    changePage.innerHTML = "<!--barre de rechercher avec suggestions-->"
                            +"<div class='wrapper'>"
                                +"<div class='search-input'>"
                                    +"<input type='text' placeholder='Rechercher...'>"
                                    +"<div class='autocom-box'>"
                                        +"<li>login</li>"
                                        +"<li>html</li>"
                                        +"<li>javascript</li>"
                                        +"<li>freelancer</li>"
                                        +"<li>web designer</li>"
                                    +"</div>"
                                    +"<div class='icon'><i class='fas fa-search'></i></div>"
                                +"</div>"
                            +"</div>"
                            +"<div class='cards_wrap'>"
                                +"<div class='card_item'>"
                                    +"<div class='card_inner'>"
                                        +"<img src='asset/img/202204191209452526.webp'>"
                                        +"<div class='title'>Black Panther</div>"
                                        +"<div class='film'>"
                                            +"<p>"
                                                +"Aliment sec pour chats<br>"
                                                +"à partir de<br>"
                                                +"<span id='prix'>24,99 €</span><br>"
                                                +"En stock"
                                            +"</p>"
                                        +"</div>"
                                    +"</div>"
                                +"</div>"
                                +"<div class='card_item'>"
                                    +"<div class='card_inner'>"
                                        +"<img src='asset/img/202204191209452526.webp'>"
                                        +"<div class='title'>Black Panther</div>"
                                        +"<div class='film'>"
                                            +"<p>"
                                                +"Aliment sec pour chats<br>"
                                                +"à partir de<br>"
                                                +"<span id='prix'>24,99 €</span><br>"
                                                +"En stock"
                                            +"</p>"
                                        +"</div>"
                                    +"</div>"
                                +"</div>"
                                +"<div class='card_item'>"
                                    +"<div class='card_inner'>"
                                        +"<img src='asset/img/202204191209452526.webp'>"
                                        +"<div class='title'>Black Panther</div>"
                                        +"<div class='film'>"
                                            +"<p>"
                                                +"Aliment sec pour chats<br>"
                                                +"à partir de<br>"
                                                +"<span id='prix'>24,99 €</span><br>"
                                                +"En stock"
                                            +"</p>"
                                        +"</div>"
                                    +"</div>"
                                +"</div>"
                                +"<div class='card_item'>"
                                    +"<div class='card_inner'>"
                                        +"<img src='asset/img/202204191209452526.webp'>"
                                        +"<div class='title'>Black Panther</div>"
                                        +"<div class='film'>"
                                            +"<p>"
                                                +"Aliment sec pour chats<br>"
                                                +"à partir de<br>"
                                                +"<span id='prix'>24,99 €</span><br>"
                                                +"En stock"
                                            +"</p>"
                                        +"</div>"
                                    +"</div>"
                                +"</div>"
                            +"</div>";
    changePage.append();
}